# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Whynot' do

  use_frameworks!
  pod 'JTAppleCalendar', '~> 7.0'

  # Pods for Whynot

  target 'WhynotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhynotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
